Запрос на добавление бизнес-логики в README
ViRGiL175/android-diner-delivery pull request #20
Opened 2020-11-16 10:57 UTC by ViRGiL175

Добавление бихнес-логики в README 

Описание стекхолдеров, которые используются при составлении историй.

## Разрешаемые Карточки

> - Resolve #145
> - Resolve #89

## Подробная информация

> Подробное описание, список источников, требования к тестированию и т.д.

2020-11-16 10:58 UTC, ViRGiL175 commented
Оно еще не готово, мне кажется, нужно как-то вкратце описать сам бизнес-процесс в общем и его специфику.

Но пока хз, как это лучше описать.

2020-11-16 11:39 UTC, Morgan-dev311 requested changes
Парочка ошибок по невнимательности, в остальном ок

2020-11-16 11:39 UTC, Morgan-dev311 commented on README.md
> +Житель города, который делает заказывает доставку в Дайнере.
"делает заказывает доставку" - что-то не то

2020-11-16 11:39 UTC, Morgan-dev311 commented on README.md
> +Серьезный, бизнесмен, хочет автоматизировать бизнес и видеть результаты автоматизации (как с т.з. повышения эффективности, так и буквально, видеть, что происходит в Дайнере), чтобы повысить эффективн
"Серьезный, бизнесмен, хочет" - вряд-ли нужны запятые

2020-11-17 08:48 UTC, ViRGiL175 commented on README.md
> +Серьезный, бизнесмен, хочет автоматизировать бизнес и видеть результаты автоматизации (как с т.з. повышения эффективности, так и буквально, видеть, что происходит в Дайнере), чтобы повысить эффективн
Это не про серьезного бизнесмена, а как две отдельные характеристики )

2020-11-18 15:37 UTC, Morgan-dev311 commented on README.md
> +Серьезный, бизнесмен, хочет автоматизировать бизнес и видеть результаты автоматизации (как с т.з. повышения эффективности, так и буквально, видеть, что происходит в Дайнере), чтобы повысить эффективн
а)) ок

2020-11-25 12:28 UTC, ViRGiL175 commented
Упаковал все компактнее, исправил опечатку.

2020-11-25 12:37 UTC, ViRGiL175 commented
Использовал адаптивное форматирование изображения и т.д., посмотрите.

2020-11-28 15:02 UTC, EsQLap approved these changes
Норм

2020-11-28 20:43 UTC, Morgan-dev311 approved these changes

2020-11-28 20:51 UTC, merged