Запрос на добавление функционала синхронизации данных с сервером
ViRGiL175/android-diner-delivery pull request #48
Opened 2020-11-23 13:25 UTC by EsQLap

Добавлен функционал синхронизации данных с сервером

> - Resolve #23

2020-11-23 16:01 UTC, Morgan-dev311 requested changes
В целом ок, но договорились использовать автодиспоз. Добавила в свою ветку.
`i23_sta_add_autodispose`

2020-11-23 18:05 UTC, Morgan-dev311 submitted a review, later dismissed
Норм

2020-11-24 20:34 UTC, ViRGiL175 requested changes
Предложил изменения в #51

2020-11-27 14:59 UTC, ViRGiL175 approved these changes

2020-11-27 14:59 UTC, Morgan-dev311 approved these changes
Мне нравится

2020-11-27 15:00 UTC, merged